# Use Node.js base image
FROM mcr.microsoft.com/devcontainers/javascript-node:20

# Optional: Set working directory
WORKDIR /workspace

# Expose Firebase CLI globally
RUN npm install -g firebase-tools